server:
  port: 8090

#Actuator
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

# thymeleaf option
spring:
  thymeleaf:
    cache: false
    mode: HTML
  # devtools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  #MariaDB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://ec2-54-180-152-11.ap-northeast-2.compute.amazonaws.com:36091/yang
    username: kwangbi
    password: ENC(0tJeTgxpxu+g0qaeHt1DqQ==) # 암호화 설정
  #JPA Option
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  #Security
  security:
    user:
      name: admin
      password: admin

#enc
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

# Log
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql=tracespring:
              jpa:
                show-sql: TRACE
            sql: TRACE